name: movie_star
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^4.0.2
  # Bloc for state management
  flutter_bloc: ^5.0.1
  # Value equality
  equatable: ^1.2.2
  # Functional programming thingies
  dartz: ^0.9.1
  # Check internet connection
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  # Local cache
  shared_preferences: ^0.5.8
  # Dart Build System for handling JSON
  json_serializable: ^3.3.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/movie.json